DirectoryPath: "public"
IgnoreSSLVerify: true
# we shouldn't be ignoring missing alt properties, but there are a few too many right now
IgnoreAltMissing: true
IgnoreInternalEmptyHash: true
IgnoreDirs:
- "apidocs"
- "zh"
- "docs/reference/api"
- "docs/reference/config"
CheckDoctype: false