apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone-pr.yaml
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ingress-config
                  key: domain
        steps:
        - image: gcr.io/jenkinsxio/hugo-extended:0.74.0-10
          name: git-submodules
          command:
          - git
          args:
          - submodule
          - update
          - --init
          - --recursive

        - image: gcr.io/jenkinsxio/hugo-extended:0.74.0-10
          name: update-content
          command: 
          - ./scripts/ci/update-content.sh

        - image: gcr.io/cloud-builders/npm
          name: install-dependencies
          command:
          - npm
          args:
          - install

        - image: gcr.io/jenkinsxio/hugo-extended:0.74.0-10
          name: build-website
          script: |
            #!/bin/sh
            hugo -d tmp-website --enableGitInfo --baseURL https://${REPO_NAME}-jx-${REPO_OWNER}-${REPO_NAME}-pr-${PULL_NUMBER}.${DOMAIN}/

        - image: gcr.io/jenkinsxio/jx-boot:3.0.738
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables

        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-and-push-image
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            /kaniko/executor --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/jx-labs-infra/jx-docs:$VERSION

        - image: gcr.io/jenkinsxio/jx-preview:0.0.122
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            # sleep infinity
            jx preview create --file charts/preview/helmfile.yaml

          env:
            - name: DOCKER_REGISTRY
              value: gcr.io

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}