apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone-pr.yaml
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ingress-config
                  key: domain
        steps:

        - image: gcr.io/jenkinsxio/hugo-extended:0.74.0-10
          name: git-submodules
          command:
          - git
          args:
          - submodule
          - update
          - --init
          - --recursive

        - image: gcr.io/jenkinsxio/hugo-extended:0.74.0-10
          name: version
          command:
          - hugo
          args:
          - version

        - image: gcr.io/cloud-builders/npm
          name: install-dependencies
          command:
          - npm
          args:
          - install

        - image: gcr.io/jenkinsxio/hugo-extended:0.74.0-10
          name: build-website
          script: |
            #!/bin/sh
            ls -al
            hugo -d tmp-website --enableGitInfo --baseURL https://${REPO_NAME}-jx-${REPO_OWNER}-${REPO_NAME}-pr-${PULL_NUMBER}.${DOMAIN}/

        - image: 18fgsa/html-proofer:latest
          name: htmlproofer
          script: |
            #!/bin/sh
            # for some reason this page has lots of bad links
            #rm ./tmp-website/docs/index.html
            # disabled --check-html as we get lots of errors about IDs
            htmlproofer ./tmp-website --allow-hash-href --disable-external --checks-to-ignore ScriptCheck --empty-alt-ignore --url-ignore "/#.*/" --file-ignore "/.*apidocs.*/,/.*\/zh.*/,/.*\/es.*/,/.*\/docs\/reference\/api.*/,/.*\/docs\/reference\/config.*/,/.*\/community\/events.*/"
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}